version: "3.7"
services: 
    postgres: 
        image: postgres
        restart: always
        ports : 
            - 5432:5432
        networks: 
            - app-network
        environment: 
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=POSTGRESQL
        volumes: 
            - ~/postgresql/data:/var/lib/postgresql/data
    application:
        build: 
            context: ./
            dockerfile: Dockerfile
        ports : 
            - 8080:8080
        depends_on : 
            - postgres
        networks: 
            - app-network
networks:
    app-network: 
        